const DATA_URL = 'https://raw.githubusercontent.com/RhoInc/data-library/master/data/clinical-trials/renderer-specific/adbds.csv';
const state = {};
let chart;
function uniq(a){ return [...new Set(a.filter(v => v !== undefined && v !== null && v !== ''))].sort((x,y)=>String(x).localeCompare(String(y), undefined, {numeric:true})); }
function mean(vals){ vals = vals.map(Number).filter(Number.isFinite); return vals.length ? vals.reduce((a,b)=>a+b,0)/vals.length : null; }
function el(tag, attrs={}, text=''){ const e=document.createElement(tag); Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v)); if(text) e.textContent=text; return e; }
function select(label, values, value){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const s=el('select'); values.forEach(v=>{const o=el('option',{value:v},v); if(v===value) o.selected=true; s.append(o);}); w.append(s); return [w,s]; }
function input(label, value=''){ const w=el('div',{class:'control'}); w.append(el('label',{},label)); const i=el('input',{type:'number', value}); w.append(i); return [w,i]; }
function table(rows, cols){ return `<table><thead><tr>${cols.map(c=>`<th>${c}</th>`).join('')}</tr></thead><tbody>${rows.slice(0,50).map(r=>`<tr>${cols.map(c=>`<td>${r[c] ?? ''}</td>`).join('')}</tr>`).join('')}</tbody></table>`; }
function participantNote(rows, allRows){ const ids=uniq(rows.map(d=>d.USUBJID)); const total=uniq(allRows.map(d=>d.USUBJID)).length; return `${ids.length} of ${total} participants shown (${total ? (100*ids.length/total).toFixed(1) : '0.0'}%).`; }

d3.csv(DATA_URL).then(data => { const measures=uniq(data.map(d=>d.TEST)); const app=document.getElementById('app'); app.innerHTML='<div class="controls"></div><div class="note" id="note"></div><div class="chartBox"><canvas id="chart"></canvas></div><div class="listing" id="listing"></div>'; const controls=app.querySelector('.controls'); const [mW,mS]=select('Measure',measures,measures[0]), [xW,xS]=select('X-axis',['VISITN','VISIT','DY'],'VISITN'), [aW,aS]=select('Treatment Group',['All',...uniq(data.map(d=>d.ARM))],'All'); controls.append(mW,xW,aW); [mS,xS,aS].forEach(x=>x.onchange=render); function render(){ const all=data.filter(d=>d.TEST===mS.value&&d.STRESN&&d[xS.value]); const rows=all.filter(d=>aS.value==='All'||d.ARM===aS.value); const ids=uniq(rows.map(d=>d.USUBJID)).slice(0,12); const xs=uniq(rows.map(d=>d[xS.value])); document.getElementById('note').textContent=participantNote(rows,all); if(chart)chart.destroy(); chart=new Chart(document.getElementById('chart'),{type:'line',data:{labels:xs,datasets:ids.map((id,i)=>({label:id,data:xs.map(x=>{const r=rows.find(d=>d.USUBJID===id&&d[xS.value]===x);return r?+r.STRESN:null}),spanGaps:true,borderColor:`hsl(${i*31},70%,45%)`}))},options:{plugins:{title:{display:true,text:mS.value}},scales:{x:{title:{display:true,text:xS.value}},y:{title:{display:true,text:'Result'}}},onClick:()=>{document.getElementById('listing').innerHTML=table(rows,['USUBJID','ARM','VISIT','VISITN','TEST','STRESN']);}}});} render(); });
